# Generated by Django 3.2.13 on 2023-05-24 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('profile_image', models.ImageField(upload_to='')),
                ('kakao_id', models.TextField(null=True)),
                ('nickname', models.TextField()),
                ('like_genre', models.TextField(choices=[('19', '모험'), ('18', '판타지'), ('17', '애니메이션'), ('16', '드라마'), ('15', '공포'), ('14', '액션'), ('13', '코미디'), ('12', '역사'), ('11', '서부'), ('10', '스릴러'), ('9', '범죄'), ('8', '다큐멘터리'), ('7', 'SF'), ('6', '미스터리'), ('5', '음악'), ('4', '로맨스'), ('3', '가족'), ('2', '전쟁'), ('1', 'TV영화'), (None, '선택')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('followings', models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
