# Generated by Django 3.2.13 on 2023-05-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_genre',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
