# Generated by Django 3.2.13 on 2023-05-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_genres',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='movies.genre'),
            preserve_default=False,
        ),
    ]
