# Generated by Django 3.2.13 on 2023-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0002_user_like_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_genres',
        ),
        migrations.AddField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(related_name='like_users', to='movies.Genre'),
        ),
    ]
