# Generated by Django 3.2.13 on 2023-05-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_like_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_genre',
        ),
    ]
