# Generated by Django 3.2.13 on 2023-05-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='watched_at',
            field=models.DateField(),
        ),
    ]
