# Generated by Django 3.2.13 on 2023-05-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_watched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='watched_people',
            field=models.IntegerField(default=1),
        ),
    ]
