# Generated by Django 3.2.13 on 2023-05-23 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_watched_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='watched_people',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
