# Generated by Django 3.2.13 on 2023-05-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_watched_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='watched_people',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
    ]
