# Generated by Django 3.2.13 on 2023-05-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genre_ids',
        ),
    ]
