# Generated by Django 3.2.13 on 2023-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_collection',
            name='collection_color',
            field=models.CharField(default='#000', max_length=10),
            preserve_default=False,
        ),
    ]
